### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by WindraiteLesd** [Lumie-fx/ayaka-plugin#1]
[2022-07-01T22:32:59.325] [ERROR] [iMac:1301951804] - 报错：ayaka-plugin-main
Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\zunzaibot\Yunzai-Bot/plugins/ayaka-plugin/resources/meta/configs/syw.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at init (file:///C:/Users/Administrator/Desktop/zunzaibot/Yunzai-Bot/plugins/ayaka-plugin-main/apps/syw.js:51:29)
    at file:///C:/Users/Administrator/Desktop/zunzaibot/Yunzai-Bot/plugins/ayaka-plugin-main/apps/syw.js:47:7
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadPlugin (file:///C:/Users/Administrator/Desktop/zunzaibot/Yunzai-Bot/lib/init.js:211:19)
    at async init (file:///C:/Users/Administrator/Desktop/zunzaibot/Yunzai-Bot/lib/init.js:49:3)
    at async Client.<anonymous> (file:///C:/Users/Administrator/Desktop/zunzaibot/Yunzai-Bot/app.js:51:3) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Administrator\\Desktop\\zunzaibot\\Yunzai-Bot/plugins/ayaka-plugin/resources/meta/configs/syw.json'
}

**Comment by Lumie-fx** [comment]
ayaka-plugin
not ayaka-plugin-main
perhaps

**Comment by WindraiteLesd** [comment]
没想到这点，我傻了

**Comment by Lumie-fx** [comment]
有个坑，没装ffmpeg用不了几个语音功能，也没加开关屏蔽，没想到有人会用这个插件hhhh
