### ISSUE TITLE
在Miao-Yunzai启动中报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Lumie-fx/ayaka-plugin#9]
```JavaScript
1|Miao-Yunzai  | [MiaoYz][22:54:03.266][INFO] ------------------
1|Miao-Yunzai  | [MiaoYz][22:54:03.266][INFO] 加载ayaka插件完成..
1|Miao-Yunzai  | [MiaoYz][22:54:03.266][INFO] ------------------
1|Miao-Yunzai  | [MiaoYz][22:54:03.270][DEBU] 载入插件 [ayaka-plugin][ayaka测试命令]
1|Miao-Yunzai  | [MiaoYz][22:54:03.270][DEBU] 载入插件 [ayaka-plugin][bilibili链接转图片]
1|Miao-Yunzai  | [MiaoYz][22:54:03.270][DEBU] 载入插件 [ayaka-plugin][-探索]
1|Miao-Yunzai  | [MiaoYz][22:54:03.270][DEBU] 载入插件 [ayaka-plugin][十连]
1|Miao-Yunzai  | [MiaoYz][22:54:03.271][DEBU] 载入插件 [ayaka-plugin][仓储]
1|Miao-Yunzai  | [MiaoYz][22:54:03.271][DEBU] 载入插件 [ayaka-plugin][圣遗物]
1|Miao-Yunzai  | [MiaoYz][22:54:03.272][DEBU] 载入插件 [ayaka-plugin][查看圣遗物]
1|Miao-Yunzai  | [MiaoYz][22:54:03.272][DEBU] 载入插件 [ayaka-plugin][圣遗物菜单]
1|Miao-Yunzai  | TypeError: GachaData.getStr is not a function
1|Miao-Yunzai  |     at gacha.init (file:///home/yuyue/Miao-Yunzai/plugins/ayaka-plugin/apps/gachaCover.js:202:15)
1|Miao-Yunzai  |     at PluginsLoader.runInit (file:///home/yuyue/Miao-Yunzai/lib/plugins/loader.js:101:27)
1|Miao-Yunzai  |     at file:///home/yuyue/Miao-Yunzai/lib/plugins/loader.js:67:16
1|Miao-Yunzai  |     at /home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4967:15
1|Miao-Yunzai  |     at baseForOwn (/home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:3032:24)
1|Miao-Yunzai  |     at /home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4936:18
1|Miao-Yunzai  |     at Function.forEach (/home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)
1|Miao-Yunzai  |     at PluginsLoader.load (file:///home/yuyue/Miao-Yunzai/lib/plugins/loader.js:60:16)
1|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|Miao-Yunzai  |     at async onlineEvent.execute (file:///home/yuyue/Miao-Yunzai/lib/events/online.js:23:5)
1|Miao-Yunzai  | [MiaoYz][22:54:03.291][ERRO] TypeError: GachaData.getStr is not a function
1|Miao-Yunzai  |     at gacha.init (file:///home/yuyue/Miao-Yunzai/plugins/ayaka-plugin/apps/gachaCover.js:202:15)
1|Miao-Yunzai  |     at PluginsLoader.runInit (file:///home/yuyue/Miao-Yunzai/lib/plugins/loader.js:101:27)
1|Miao-Yunzai  |     at file:///home/yuyue/Miao-Yunzai/lib/plugins/loader.js:67:16
1|Miao-Yunzai  |     at /home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4967:15
1|Miao-Yunzai  |     at baseForOwn (/home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:3032:24)
1|Miao-Yunzai  |     at /home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4936:18
1|Miao-Yunzai  |     at Function.forEach (/home/yuyue/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)
1|Miao-Yunzai  |     at PluginsLoader.load (file:///home/yuyue/Miao-Yunzai/lib/plugins/loader.js:60:16)
1|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|Miao-Yunzai  |     at async onlineEvent.execute (file:///home/yuyue/Miao-Yunzai/lib/events/online.js:23:5)
```

**Comment by YuYue-Amatsuki** [comment]
TRSS-Yunzai启动也同样报错
